### ISSUE TITLE
Issues for funtoo(gentoo) linux

### ISSUE THREAD

**Issue by hsbt** [itamae-kitchen/mitamae#100]
1. `package` resource is not working with funtoo and gentoo linux. `mitamae` always tries to install it.

2. `service` resource is also not working with funtoo and gentoo linux. They uses `OpenRC` now. so `mitamae` needs to invoke `rc-update`. But the current `mitamae` uses `chkconfig`

**Comment by k0kubun** [comment]
> package resource is not working with funtoo and gentoo linux. mitamae always tries to install it.

My current understanding is that `sudo emerge eix && sudo eix-update` is the only way to make it work. Please update your recipe to run them before any other `package` resources.

> service resource is also not working with funtoo and gentoo linux. They uses OpenRC now. so mitamae needs to invoke rc-update. But the current mitamae uses chkconfig

Using `rc-update` is partially implemented in specinfra https://github.com/mizzy/specinfra/blob/5dc5bb07edb03efc2bfb73c6a7d2107e0b8ef293/lib/specinfra/command/gentoo/base/service.rb. But most of actions to update a service seem to be not supported. I'll try to fix them.

**Comment by k0kubun** [comment]
Fixed the `service` problem in v1.11.5 too.

**Comment by hsbt** [comment]
Thanks a lot.
