### ISSUE TITLE
mitamae 1.12.6 failing to do `rake compile` on Solaris 10

### ISSUE THREAD

**Issue by junaruga** [itamae-kitchen/mitamae#113]
I see the mitamae version 1.12.6 `rake compile` fails on the Solaris 10. Here is [the full log](https://gist.github.com/junaruga/0140040a97d18bdfcb548d578f1f3426#file-ruby-solaris-sol10-mitamae-build_5-log-L1309)

```
-bash-3.2$ cat /etc/release 
                   Oracle Solaris 10 1/13 s10s_u11wos_24a SPARC
  Copyright (c) 1983, 2013, Oracle and/or its affiliates. All rights reserved.
                            Assembled 17 January 2013

-bash-3.2$ cd /tmp/mitamae_5

-bash-3.2$ git checkout v1.12.6

-bash-3.2$ gcc --version
gcc (GCC) 5.5.0 
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

-bash-3.2$ rake compile 2>&1 | tee rake.log
...
regint.h:220:22: error: implicit declaration of function 'alloca' [-Werror=implicit-function-declaration]
         # define xalloca     alloca      
                              ^
```

**Comment by junaruga** [comment]
There is `alloca.h` on the environment.

```
-bash-3.2$ ls /usr/include/alloca.h
/usr/include/alloca.h
```

I added the line `#include <alloca.h>` before the error line `# define xalloca     alloca`.

```
-bash-3.2$ vi ./mruby/build/host/mrbgems/mruby-onig-regexp/onigmo-6.2.0/regint.h
...
#include <alloca.h>
...
```

Then after running `rake compile` again, I could build it.

```
-bash-3.2$ rake compile
...
-bash-3.2$ ls -l mruby/build/host/bin/mitamae
-rwxr-xr-x 1 ruby other 11852860 Jun 14 04:12 mruby/build/host/bin/mitamae
```

**Comment by k0kubun** [comment]
Can we either report this to Onigmo or upgrade Onigmo in mruby-onig-regexp if it's already fixed in the latest version? This is not really actionable from the mitamae side until the upstream is fixed.

**Comment by junaruga** [comment]
OK. I will check and report it.

**Comment by k0kubun** [comment]
Closing as this is not actionable in this repository at this moment. Please reopen when we can pull a fix in the upstream.
