### ISSUE TITLE
Can't run tests due to invalid libyaml.a

### ISSUE THREAD

**Issue by refi64** [itamae-kitchen/mitamae#117]
If I run `rake test:integration`, I get:

```
[...]
PKG-CONFIG onigmo 
PKG-CONFIG oniguruma 
CC    build/repos/host/mruby-yaml/src/yaml.c -> build/host/mrbgems/mruby-yaml/src/yaml.o
AR    build/host/lib/libmruby.a 
LD    build/host/bin/mitamae 
/usr/bin/ld: /home/mruby/code/mruby/build/host/mrbgems/mruby-yaml/libyaml/build/lib//libyaml.a(api.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
[....]
/usr/bin/ld: /home/mruby/code/mruby/build/host/mrbgems/mruby-yaml/libyaml/build/lib//libyaml.a(reader.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
rake aborted!
Command failed with status (1): [gcc -L/home/mruby/code/mruby/build/host/mr...]
/home/mruby/code/mruby/lib/mruby/build/command.rb:37:in `_run'
/home/mruby/code/mruby/lib/mruby/build/command.rb:217:in `run'
/home/mruby/code/mruby/tasks/bin.rake:17:in `block (4 levels) in <top (required)>'
/home/mruby/code/mruby/Rakefile:43:in `block in <top (required)>'
Tasks: TOP => build => /home/mruby/code/mruby/bin/mitamae => /home/mruby/code/mruby/build/host/bin/mitamae
(See full trace by running task with --trace)

An error occurred in a `before(:suite)` hook.
[...]
```

For some even stranger reason, this *does* work if I build on my host system (Fedora 36), just...not in the container.

**Comment by k0kubun** [comment]
> this does work if I build on my host system (Fedora 36), just...not in the container.

Do you mean you want to run the integration test, which runs a container, from a container? It's technically possible, but I don't have any motivation to support it in this repository (ref: https://stackoverflow.com/questions/27879713/is-it-ok-to-run-docker-from-inside-docker). While I might accept a patch to make it work, as long as tests run on the maintainers' environment and CI, which everybody could use, it's not a problem when maintaining mitamae. Please run it on your host system or just use CI.

**Comment by refi64** [comment]
Sorry for the lack of clarification: I'm referring to how the specs *build* inside a container unless I set `SKIP_MITAMAE_COMPILE=1`.

**Comment by k0kubun** [comment]
So you actually meant `rake compile` succeeds on your host machine but not on `k0kubun/mitamae-dockcross:linux-x86_64`, right? IIRC, it succeeded on my Ubuntu 20.04 machine yesterday, and it has worked fine on CI too. Thus it's likely about your setup, not this repository's problem.

Since it's currently reproducing only in your environment, this issue is not actionable on my end. You should at least provide how to reproduce it without assuming your current setup, but this issue is not filed that way. One option to achieve it is to reproduce it on GitHub Actions.
