### ISSUE TITLE
Should it be launched as root?

### ISSUE THREAD

**Issue by ineu** [itamae-kitchen/mitamae#129]
I have the following snippet:
```ruby
template "/boot/loader/entries/arch.conf" do
  user "root"
  source "../files/boot.erb"
end
```
When I execute it as a user via itamae (`itamae local ...`), it works fine. But when I execute the same code as a user via mitamae, I get the error:
```
Permission denied - open /tmp/1702644793.881364 (Errno::EACCES)
```

So the question is: is it a bug in mitamae, or is mitamae intended to be run as root?

**Comment by k0kubun** [comment]
It's the intended behavior. If you decide to use a root user with user "root", mitamae itself needs to be able to switch to root. If you don't use a root user from a recipe, you don't need it. It's just up to recipes, and it's impossible for a random program like mitamae to escalate privilege.

**Comment by ineu** [comment]
I see, thanks for the response. Would it make sense to note it in the README?

However, I have to disagree on:
> it's impossible for a random program like mitamae to escalate privilege.

as there's sudo. Ansible can use it, hocho can use it, why can't mitamae? (i'm not familiar with the internal of mitamae and don't know if it spawns external processes at all)

**Comment by k0kubun** [comment]
Ah, now I get what you're talking about. So you want mitamae to prompt you in the middle of mitamae execution whenever necessary. 

In that case, yes, it's something we deliberately don't support; if your recipe needs root, you're suppose to run mitamae as root. So it makes sense to mention it somewhere in the README. I'd accept a PR that adds such documentation.

**Comment by ineu** [comment]
> So you want mitamae to prompt you in the middle of mitamae execution whenever necessary.

Not really, that would be a poor user experience. What I mean is rather this
```
# /etc/sudoers
%wheel ALL=(ALL) NOPASSWD:ALL # or maybe not "ALL", but specifically "mitamae"
```

Thus by default recipes could be executed as a user who belongs to the "wheel" group, but when needed, root can be achieved without interruption.

This makes most sense with `itamae/mitamae local`, to provision a workstation. Less so for servers.
