### ISSUE TITLE
"apt update" not executed by "notifies"

### ISSUE THREAD

**Issue by ineu** [itamae-kitchen/mitamae#130]
I have the following snippet
```ruby
file "/etc/apt/sources.list.d/zabbly-incus-stable.sources" do
  content <<~EOF
    ... skipped for brevity
  EOF

  notifies :run, "execute[apt update]", :immediately
end

execute("apt update") { action :nothing }
```
which never actually runs `apt update` when the file is changed. But it works in all these cases:

1. if I change `apt update` to `apt-get update`
2. if I use the absolute path (`execute[/usr/bin/apt update]`)
3. even if I make the `execute` resource do something completely unrelated, like this:
  ```ruby
  execute("apT update") {
    command "touch /tmp/foo"
    action :nothing
  }
  ```
  
Note the capital `T` in the name: it's the only difference that actually make the resource run. Looks like the problem is not related to the actual command being executed. Something is wrong with the exact `apt update` string.

**Comment by k0kubun** [comment]
works fine for me.

```ruby
$ bin/mitamae version
mitamae v1.14.0

$ cat /tmp/a.rb
file "/etc/apt/sources.list.d/zabbly-incus-stable.sources" do
  content <<~EOF
    # ... skipped for brevity
  EOF

  notifies :run, "execute[apt update]", :immediately
end

execute("apt update") { action :nothing }

$ sudo bin/mitamae local /tmp/a.rb
 INFO : Starting mitamae...
 INFO : Recipe: /tmp/a.rb
 INFO :   file[/etc/apt/sources.list.d/zabbly-incus-stable.sources] exist will change from 'false' to 'true'
 INFO :   diff:
 INFO :   --- /dev/null 2024-01-23 09:50:55.311522105 -0800
 INFO :   +++ /tmp/1706045693.091229    2024-01-23 13:34:53.086955047 -0800
 INFO :   @@ -0,0 +1 @@
 INFO :   +# ... skipped for brevity
 INFO :   Notifying run to execute resource 'apt update' (immediately)
 INFO :   execute[apt update] executed will change from 'false' to 'true'

$ sudo bin/mitamae local /tmp/a.rb
 INFO : Starting mitamae...
 INFO : Recipe: /tmp/a.rb

$ cat /tmp/b.rb
file "/etc/apt/sources.list.d/zabbly-incus-stable.sources" do
  content <<~EOF
    # ... skipped for brevity (edited)
  EOF

  notifies :run, "execute[apt update]", :immediately
end

execute("apt update") { action :nothing }

$ sudo bin/mitamae local /tmp/b.rb
 INFO : Starting mitamae...
 INFO : Recipe: /tmp/b.rb
 INFO :   diff:
 INFO :   --- /etc/apt/sources.list.d/zabbly-incus-stable.sources       2024-01-23 13:34:53.086955047 -0800
 INFO :   +++ /tmp/1706045711.044741    2024-01-23 13:35:11.038842626 -0800
 INFO :   @@ -1 +1 @@
 INFO :   -# ... skipped for brevity
 INFO :   +# ... skipped for brevity (edited)
 INFO :   Notifying run to execute resource 'apt update' (immediately)
 INFO :   execute[apt update] executed will change from 'false' to 'true'
```

Can you run the same commands (with the above `/tmp/a.rb` and `/tmp/b.rb`, and maybe with `--log-level=debug`) and report the result as I did?

**Comment by ineu** [comment]
Ok, found the reason, thanks for pointing me at the `--log-level` option.

I use `execute[apt update]` in many files and expected the resources to be file-scoped. However, they seem to all live in a global scope, that's why my `notifies` invoked `execute[apt update]` resource from another file which was `include_recipe`'d before:
```
execute "apt update" do
  only_if "find /var/lib/apt/lists/ -maxdepth 0 -type d -empty | grep -q ^" # has never been updated before
end
```
which was skipped by `only_if`.

The global scope makes sense when you think about it in the Ruby context, but it can lead to such silent failures. Would it make sense for a new feature to raise an exception if the same resource was already defined?

**Comment by k0kubun** [comment]
As a re-implementation of Itamae, we generally don't introduce mitamae-specific features or incompatibilities. Can you open a pull request or an issue to Itamae first if you want the feature in mitamae? Thank you.

**Comment by ineu** [comment]
Yeah, I realise it. Was wondering if such a feature would make sense for you.

**Comment by k0kubun** [comment]
Running the same thing twice in different locations might have a legitimate use case, so I wouldn't like that breaking change. If I were to build Itamae from scratch, I would restrict `notifies` to impact only resources in the same recipe. But that's a breaking change too.

I'll follow whatever the current Itamae maintainers think is reasonable and decide to implement. You may look at what Chef does for inspiration (I'm not sure what it does for this problem, so you need to look at it yourself).

**Comment by ineu** [comment]
Got it, thank you.
