### ISSUE TITLE
File.Stat not working as expected

### ISSUE THREAD

**Issue by timuckun** [itamae-kitchen/mitamae#75]
I have the following code.

```ruby
destination = File.expand_path "~/.spacemacs"
if File.exists?(destination)
  s = File.stat(destination)
  puts s.ftype
  puts s.symlink?
  puts File.realpath(destination)
  puts File.readlink(destination)
end
```

This gives a very unexpected output

```bash
file
false
/opt/tim/dorkish/x1/dotfiles/spacemacs/.spacemacs
dorkish/x1/dotfiles/spacemacs/.spacemacs
```

The filetype is being reported as "file" and it should be "link"
the realpath call returns the full path of the real file and the readlink returns the relative path of the real fie.

I am not sure what is going on here but clearly both the filetype and the symlink? calls are returning unexpected values.

**Comment by k0kubun** [comment]
Please report that to upstream first https://github.com/ksss/mruby-file-stat, and ask me to upgrade the library once it's fixed.
