### ISSUE TITLE
Can somebody please explain why the following doesn't work

### ISSUE THREAD

**Issue by timuckun** [itamae-kitchen/mitamae#76]
I have this code

```ruby
#do the directories in this order. Common first and if there is a conflict the host overrides
[common_dir, host_dir].each do |dir|
  #create the directory and manifest if it doesn't exist
  directory dir do
    action :create
  end

  manifest_file = File.join(dir, manifest_file_name)
  unless File.exists?(manifest_file)
    file manifest_file do
      puts 'here'
      action :create
      content "---\n"
    end
  end
  
 manifest = YAML.load(File.read(manifest_file))
 manifest ||= []

  manifest.each do |dotfile|
   smart_symlink_dotfile dotfile do
     source_dir dir
   end
  end
end
```

When I run this I get the output of the "puts 'here'" command but I also get an error message "No such file or directory " when the File.read line hits.  If I comment out that line the directory and the manifest file are created properly.

It's looking to me like the files are being created lazily so they are not ready by the time I try and access them. How can I assure that they exist right away? Should I just shell out to echo or something? Would that work?

**Comment by k0kubun** [comment]
mitamae's directive isn't immediately executed while recipe script is evaluated. This is an intended behavior. Use `local_ruby_block`.
